import type { DriveApiProductRecord } from "@/types/driveApi";

export const DRIVE_MOCK_PRODUCT_CATALOG: DriveApiProductRecord[] = [
  {
    sku: "cf-lait-1l",
    name: "Lait demi-écrémé UHT",
    priceEuro: 1.09,
    aisleLabel: "Frais · Laitiers",
    category: "frais",
    qualityScore: "B",
    glycemicIndex: 35,
    isLowGlycemic: true,
    isGlutenFree: true,
    connectorId: "carrefour",
  },
  {
    sku: "cf-pain-complet",
    name: "Pain complet aux céréales",
    priceEuro: 2.45,
    aisleLabel: "Boulangerie",
    category: "épicerie",
    qualityScore: "A",
    glycemicIndex: 50,
    isGlutenFree: false,
    isLowSodium: true,
    connectorId: "carrefour",
  },
  {
    sku: "le-riz-basmati",
    name: "Riz basmati",
    priceEuro: 3.29,
    aisleLabel: "Épicerie · Féculents",
    category: "épicerie",
    qualityScore: "B",
    glycemicIndex: 58,
    isGlutenFree: true,
    connectorId: "leclerc",
  },
  {
    sku: "le-saumon-fume",
    name: "Saumon fumé",
    priceEuro: 4.99,
    aisleLabel: "Frais · Poissonnerie",
    category: "frais",
    qualityScore: "C",
    isLowSodium: false,
    isGlutenFree: true,
    connectorId: "leclerc",
  },
  {
    sku: "au-tomates-grappes",
    name: "Tomates grappes",
    priceEuro: 2.89,
    aisleLabel: "Frais · Légumes",
    category: "frais",
    qualityScore: "A",
    glycemicIndex: 15,
    isLowGlycemic: true,
    connectorId: "auchan",
  },
  {
    sku: "au-eau-minerale",
    name: "Eau minérale 6×1,5 L",
    priceEuro: 1.79,
    aisleLabel: "Boissons",
    category: "boissons",
    qualityScore: "A",
    isLowSodium: true,
    connectorId: "auchan",
  },
];

/** Lot injecté par l'action démo « Simuler push API Drive ». */
export const DEMO_DRIVE_API_PUSH_BATCH: DriveApiProductRecord[] = [
  {
    sku: "demo-yaourt-grec",
    name: "Yaourt grec nature",
    priceEuro: 1.49,
    aisleLabel: "Frais · Laitiers",
    category: "frais",
    qualityScore: "A",
    glycemicIndex: 30,
    isLowGlycemic: true,
    isGlutenFree: true,
    connectorId: "carrefour",
  },
];
